New rent precedent
penamarth/bsbo-13-22_team1_var8 pull request #12
Opened 2024-11-04 09:03 UTC by vl1856

2024-11-08 11:17 UTC, DevorCapitaux requested changes

2024-11-08 11:17 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +Квартиросъемщик. Хочет иметь возможность иметь возможность удобно оплачивать квартиру через приложение и оставлять заявку на съем.
"иметь возможность" повторяется дважды

2024-11-08 11:17 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +Владелец квартиры. Хочет иметь возможность получать, как можно больше о квартиросъмщике и иметь удобную
Может "с квартиросъёмщика"?

2024-11-08 11:17 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +1. Квартиросъемщик регистрируется на платформе оставляя информацию о себе.
Предлагаю заменить слово "платформа" на "приложение" (как в пунктах ниже), чтобы быть более конкретным.

2024-11-08 11:17 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +1. Квартиросъемщик регистрируется на платформе оставляя информацию о себе.
Аналогично заменить "на платформе" на "в приложении".

2024-11-08 11:17 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +- Владелец получает оплату и квартиросъмщик заселяется.
Пропущена ё в "квартиросъёмщик".

2024-11-08 11:17 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +2. Квартиросъещик хочет арендовать кватиру и ставит отклик на желаемую.
Пропущена м в "квартиросъёмщик".

2024-11-08 11:17 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +5. Квартиросъещик переводит деньги на виртуальную карту.
"Квартиросъёщик" -> "Квартиросъёмщик".

2024-11-08 11:17 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +2. Квартиросъещик хочет арендовать кватиру и ставит отклик на желаемую.
"Квартиросъёщик" -> "Квартиросъёмщик".

2024-11-14 09:03 UTC, Tr11nk approved these changes

2024-11-14 09:10 UTC, DevorCapitaux requested changes

2024-11-14 09:10 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +Квартиросъемщик. Хочет иметь возможность иметь удобно оплачивать квартиру через приложение и оставлять заявку на съем.
Теперь одно "иметь" лишнее

2024-11-14 09:10 UTC, DevorCapitaux commented on use_cases/rentflat/rentflat.md
> +1. Квартиросъемщик регистрируется на платформе, оставляя информацию о себе.
"на платформе" -> "в приложении"

2024-11-14 20:55 UTC, DevorCapitaux approved these changes

2024-11-14 20:56 UTC, merged